# Generated by Django 3.2.4 on 2021-06-19 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('in_good_hands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('1', 'Fundacja'), ('2', 'Organizacja Pozarządowa'), ('3', 'Zbiórka Lokalna')], default='1', max_length=1)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='in_good_hands.category')),
            ],
        ),
    ]
